### PR TITLE
Changes for landing https://github.com/dart-lang/sdk/issues/32161

### PR DESCRIPTION
**Pull request by MichaelRFairhurst**
Add void declarations to methods with implicit dynamic returning void
values, which *may* be illegal in dart 2, but in either case, expresses
the current intent better.

### CODE REVIEW

**Comment by MichaelRFairhurst** [comment]
Thanks @jtmcdole. Would you be able to publish these changes soon as well?

**Comment by jtmcdole** [comment]
Yeah, I'll publish a new version tomorrow morning - I was out of office today.

**Comment by MichaelRFairhurst** [comment]
Friendly ping

**Comment by jtmcdole** [comment]
Done.
https://pub.dartlang.org/packages/ansicolor

**Pull request merged**
