### PR TITLE
Issue #10: Clean up style

### PR DESCRIPTION
**Pull request by jtmcdole**
Cleanup comment style, move ansi_demo to bin/demo.dart, update to use the
new dart test library.

### CODE REVIEW

**Comment by pulyaevskiy** [comment]
+1.
Nice to see activity here!

Any chances to merge/publish this some time soon?

**Comment by pulyaevskiy** [comment]
Awesome, thanks!
Looking forward for updated version in Pub!

Also, will be happy to help with supporting this library (cleaning up open issues, submitting PRs etc).

**Comment by jtmcdole** [comment]
Assuming there wasn't something else the original reviewer was asking for. I can make a new version tonight and push to pub. Color me (pun intended) surprised that someone was using this :)

**Comment by pulyaevskiy** [comment]
There are a couple alternatives on Pub which can be used:

- Console: heavy library implementing all-things about terminal.
- Colorize: Similar to this one, but API is a bit more verbose. No recent activity there as well.

If I'm a user of `args` package then `console` is not an option. Colorize can be used, but API provided by this library is much better, in my opinion.

**Comment by jtmcdole** [comment]
Have you signed the google cla?

**Comment by pulyaevskiy** [comment]
I did when contributed a PR to the SDK.

**Comment by jtmcdole** [comment]
Great, I'd love extra pull requests if you have something you want to see
done. I'm not a code curmudgeon, I've just been busy elsewhere :)

**Comment by pulyaevskiy** [comment]
Sounds great!
I've just started using this library. Need to spend a little bit more time with it and will get back with some suggestions.

Thanks!

**Pull request merged**
